name: Run lint, test and build

env:
  CI: true
  MONGO_INITDB_DATABASE: 'database'

on: pull_request
jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - run: printenv
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.0'
          mongodb-port: 27017
          mongodb-username: username 
          mongodb-password: password 
          mongodb-db: database 

      - run: yarn
      - run: yarn bootstrap
      - run: yarn lint

      - run: yarn test:unit

      - run: yarn build
        
      - run: yarn test:e2e

